gulp:
  entry: ./src/Draft.js

  directories:
    dist: dist
    vendor: public/vendor/draft

  tests:
    temp: tests/build/draft.js

  dependencies:
    - public/vendor/d3/d3.js
    - public/vendor/lodash/lodash.js
    - public/vendor/mousetrap/mousetrap.js

  names:
    dev: draft.js
    prod: draft.min.js

  all:
    - ./src/*.js
    - ./src/**/*.js
    - ./src/**/**/*.js