language: node_js

node_js:
  - '5.9'
  - '5.10'
  - '5.11'

addons:
  firefox: '45.0'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: A9Lxru9uzHXIZ7m0odZLUw2XCmQmnonicvyzubR3ONowf2HK75qeoozCkNiElT0AUYHKGw/tQi2eE0iyUVKfUKa7+BzUFlcNCTO8J9tmW7pfWspmD1ll3BuxdcorPkd2nbxs9xmhBG9NDLui2YUT5YHQvFshucLFaoq1+VVXLC8=
  app: app-draft
  on:
    repo: Wildhoney/Draught
