language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: A9Lxru9uzHXIZ7m0odZLUw2XCmQmnonicvyzubR3ONowf2HK75qeoozCkNiElT0AUYHKGw/tQi2eE0iyUVKfUKa7+BzUFlcNCTO8J9tmW7pfWspmD1ll3BuxdcorPkd2nbxs9xmhBG9NDLui2YUT5YHQvFshucLFaoq1+VVXLC8=
  app: getblueprint
  on:
    repo: Wildhoney/Blueprint
